spring:
  application:
    name: bookapp

#DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console

#JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#env
api:
  key: ${API_KEY}
#server
server:
  port: 8080
  servlet:
    session:
      timeout: 60m

#log
logging:
  level:
    org:
      springdoc: DEBUG
      springframework:
        web: DEBUG

#swagger
springdoc:
  api-docs:
    enabled: true
  override-with-genric-response: false
  swagger-ui:
    path: /swagger
    enabled: true


